"""add file_path to notebooks

Revision ID: 4fc6b4aac154
Revises: 5e9c812e05dd
Create Date: 2025-04-09 18:13:36.196160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc6b4aac154'
down_revision: Union[str, None] = '5e9c812e05dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'file_path')
    # ### end Alembic commands ###
